default:
  before_script:
    - apk add bash
    - pip install nose

py2.7-core:
  image: python:2.7
  variables:
    HDL_TEST_SET: core
  before_script:
    - pip install nose
  script:
    - ./devscripts/run_tests.sh

py3.6-core:
  image: python:3.6-alpine
  variables:
    HDL_TEST_SET: core
  script:
    - ./devscripts/run_tests.sh

py3.7-core:
  image: python:3.7-alpine
  variables:
    HDL_TEST_SET: core
  script:
    - ./devscripts/run_tests.sh

py3.8-core:
  image: python:3.8-alpine
  variables:
    HDL_TEST_SET: core
  script:
    - ./devscripts/run_tests.sh

py3.9-core:
  image: python:3.9-alpine
  variables:
    HDL_TEST_SET: core
  script:
    - ./devscripts/run_tests.sh

py3.9-download:
  image: python:3.9-alpine
  variables:
    HDL_TEST_SET: download
  allow_failure: true
  script:
    - ./devscripts/run_tests.sh

jython-core:
  image: openjdk:11-slim
  variables:
    HDL_TEST_SET: core
  allow_failure: true
  before_script:
    - apt-get update
    - apt-get install -y wget
    - ./devscripts/install_jython.sh
    - export PATH="$HOME/jython/bin:$PATH"
  script:
    - ./devscripts/run_tests.sh

# uncomment once the images are available
# https://github.com/microsoft/playwright-python/issues/338
# playwright-tests-core:
#   image: mcr.microsoft.com/playwright-python:focal
#   variables:
#     HDL_TEST_SET: core
#   script:
#     - ./devscripts/run_tests.sh

# playwright-tests-download:
#   image: mcr.microsoft.com/playwright-python:focal
#   variables:
#     HDL_TEST_SET: download
#     HDL_TEST_PLAYWRIGHT_DOWNLOAD: 1
#   script:
#     - ./devscripts/run_tests.sh
