default:
  before_script:
    - apk add bash
    - pip install nose

pypy3.6-core:
  image: pypy:3.6-slim
  variables:
    HDL_TEST_SET: core
  before_script:
    - apt-get update && apt-get install -y bash && apt-get clean
    - pip install nose
  script:
    - ./devscripts/run_tests.sh

pypy3.7-core:
  image: pypy:3.7-slim
  variables:
    HDL_TEST_SET: core
  before_script:
    - apt-get update && apt-get install -y bash && apt-get clean
    - pip install nose
  script:
    - ./devscripts/run_tests.sh

py3.6-core:
  image: python:3.6-alpine
  variables:
    HDL_TEST_SET: core
  script:
    - ./devscripts/run_tests.sh

py3.7-core:
  image: python:3.7-alpine
  variables:
    HDL_TEST_SET: core
  script:
    - ./devscripts/run_tests.sh

py3.8-core:
  image: python:3.8-alpine
  variables:
    HDL_TEST_SET: core
  script:
    - ./devscripts/run_tests.sh

py3.9-core:
  image: python:3.9-alpine
  variables:
    HDL_TEST_SET: core
  script:
    - ./devscripts/run_tests.sh

py3.9-download:
  image: python:3.9-alpine
  variables:
    HDL_TEST_SET: download
  allow_failure: true
  script:
    - ./devscripts/run_tests.sh


playwright-tests-core:
  image: mcr.microsoft.com/playwright:focal
  variables:
    HDL_TEST_SET: core
  before_script:
    - apt-get update && apt-get install -y bash && apt-get clean
    - pip install nose
  script:
    - ./devscripts/run_tests.sh

playwright-tests-download:
  image: mcr.microsoft.com/playwright:focal
  variables:
    HDL_TEST_SET: download
    HDL_TEST_PLAYWRIGHT_DOWNLOAD: 1
  allow_failure: true
  before_script:
    - apt-get update && apt-get install -y bash && apt-get clean
    - pip install nose
  script:
    - ./devscripts/run_tests.sh
